### PR TITLE
#82: Fixed strings, added loading of klasses

### LINKED ISSUE #82: instr2Raw.cpp:11: add template parameter by format and...
The puzzle `54-89a87874` from #54 has to be resolved: 

https://github.com/Tea-club/ChaiVM/blob/fb013fba8e396144f245be94b4d64d205f0b866d/src/ChaiVM/utils/instr2Raw.cpp#L11-L11

The puzzle was created by Lev Bagryansky on 19-Feb-24. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by levBagryansky**
closes #82 
- fixed strings
- added klasses to bytecode

### CODE REVIEW

**Comment by levBagryansky** [comment]
@c71n93 pls review

File: include/ChaiVM/interpreter/code-manager/klass.hpp [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+#include "ChaiVM/memory/linear-buffer.hpp"
+#include "ChaiVM/types.hpp"
+
+namespace chai::interpreter {
+
+union Data {
+    int64_t ch_int_;
+    double ch_float_;
+    chsize_t ch_ref_;
+};
```
Comment (c71n93) [inline include/ChaiVM/interpreter/code-manager/klass.hpp:16]: @levBagryansky why do we need this union?

File: include/ChaiVM/interpreter/code-manager/code-manager.hpp [hunk 2]
```diff
@@ -38,24 +39,45 @@ class CodeManager final {
...
+
+    /**
+     * Get string by constant that provided constant pool.
+     * Usually we take constant from constant pool directly. In case of string
+     * there is just 64-bit number that encodes String. Use this method to get
+     * string by this number.
+     * @param reg_val Number from constant pool.
+     * @return String.
+     */
+    const std::string &getCnstStringByReg(chsize_t reg_val);
```
Comment (c71n93) [inline include/ChaiVM/interpreter/code-manager/code-manager.hpp:63]: @levBagryansky It is not obvious why this function uses "Reg". It only became clearer when you start browsing code and see how this function is used in `executor`. Consider to make name a little more obvious. Or add explanation to documentation, please (not a good option)

File: include/ChaiVM/utils/file-format/klass-info.hpp [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+#include "ChaiVM/types.hpp"
+#include "ChaiVM/utils/io-bytes.hpp"
+
+namespace chai::utils::fileformat {
+
+enum FieldTag : uint8_t { I64 = 1, F64 = 2 };
+
+struct FieldInfo {
+    interpreter::Immidiate name_;
+    uint8_t isObject_;
```
Comment (c71n93) [inline include/ChaiVM/utils/file-format/klass-info.hpp:16]: @levBagryansky why can't you make this field of type `FieldTag`?

Comment (levBagryansky) [reply include/ChaiVM/utils/file-format/klass-info.hpp:16]: @c71n93 `0` means that it is primitive type.  `FieldTag` is in the field `tagOrKlassNum_`.

File: include/ChaiVM/interpreter/code-manager/code-manager.hpp (hunk 2 above)
Comment (levBagryansky) [reply include/ChaiVM/interpreter/code-manager/code-manager.hpp:63]: @c71n93 I don't know how. Maybe you suggest smth here.

File: include/ChaiVM/interpreter/code-manager/klass.hpp (hunk 1 above)
Comment (levBagryansky) [reply include/ChaiVM/interpreter/code-manager/klass.hpp]: @c71n93 Removed

File: include/ChaiVM/utils/file-format/klass-info.hpp (hunk 3 above)
Comment (c71n93) [reply include/ChaiVM/utils/file-format/klass-info.hpp:16]: @levBagryansky So, as I understood, klass num can't be 1 or 2?

File: include/ChaiVM/interpreter/code-manager/code-manager.hpp (hunk 2 above)
Comment (c71n93) [reply include/ChaiVM/interpreter/code-manager/code-manager.hpp:63]: @levBagryansky maybe `getStringByStringPoolPos(chsize_t pos)`? It's too verbose, but makes much more sense for me.

**Review by c71n93 — DISMISSED** [review]
norm

File: include/ChaiVM/utils/file-format/klass-info.hpp (hunk 3 above)
Comment (levBagryansky) [reply include/ChaiVM/utils/file-format/klass-info.hpp:16]: No, it can. If `isObject` is 1 that `tagOrKlassNum_` is klass number (0, ..). Otherwise `tagOrKlassNum_` this is int or float (1 or 2)
